### ISSUE TITLE
Upon logging-in, Mobile jQuery theme sticks around & requires reload

### ISSUE THREAD

**Issue by skorasaurus** [cuyahoga-tap/cuyasurvey-drupal#10]

**Comment by jeffschuler** [comment]
jQuery Mobile takes over what happens when links are clicked, such as for triggering a page transition effect like the default "slide" -- via "link binding".

When a link or form submission like login changes us from the jQuery Mobile theme to another theme, this link binding is hijacking the switch of themes. A normal reload of the page (or going to the page directly through the browser address bar) circumvents this.

Enabling/Disabling link binding can be done in the module settings ( admin/config/system/jquerymobile_ui ) and this result can be seen in page head:

``` html
<script type="text/javascript">
<!--//--><![CDATA[//><!--
var jqm = jQuery.noConflict();
jqm(document).bind("mobileinit", function(){
    jqm.mobile.linkBindingEnabled = "false";
});
//--><!]]>
</script>
```

However, this wasn't working... We had "fixed" the module in e3d2f7f4c093a65fb82483df3a24cda4c3678006 to balance quotes around this var setting by adding another quote. We should've removed the existing one as this should be set as a bool, (false) not a string ("false"). I fixed that here: f59cc6f7e5d46c8464fcf534887102e54e9b2450

So now we can successfully turn link binding off, which I'll do. This means we don't get a nice little slide when the user submits the survey. We could set the transition on this form submission manually, or figure out how to fix the module to avoid this issue.

**Comment by jeffschuler** [comment]
Added new patch to module issue on drupal.org: http://drupal.org/node/1416130#comment-5529922

**Comment by jeffschuler** [comment]
Also need to disable Ajax on the module settings form, as it's not a page transition from form submission...

Changed in staging and production.

(We could set these vars in settings.php too.)

Fixed, though.
